// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.AcronymExpander
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("acronym")]
        public string Acronym { get; set; }

        [JsonProperty("expansions")]
        public MostCommon[] Expansions { get; set; }

        [JsonProperty("most_common")]
        public MostCommon MostCommon { get; set; }

        [JsonProperty("source")]
        public string Source { get; set; }

        [JsonProperty("context_provided")]
        public string ContextProvided { get; set; }
    }

    public partial class MostCommon
    {
        [JsonProperty("expansion")]
        public string Expansion { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("category")]
        public string Category { get; set; }
    }
}
